# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='country',
            field=models.CharField(default='Russia', max_length=60, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
