# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20160704_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='period',
            field=models.CharField(max_length=50, verbose_name='Period of work'),
        ),
    ]
