# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_education_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='site',
            field=models.URLField(blank=True, max_length=64, verbose_name='Site'),
        ),
    ]
