# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20160706_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=50, verbose_name='Name')),
                ('employer_site', models.URLField(blank=True, max_length=64, verbose_name='Site')),
                ('employer_location', models.CharField(max_length=300, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stp_name', models.CharField(max_length=80, verbose_name='Place of study')),
                ('stp_site', models.URLField(blank=True, max_length=64, verbose_name='Site')),
                ('stp_location', models.CharField(max_length=300, verbose_name='Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='location',
        ),
        migrations.RemoveField(
            model_name='education',
            name='site',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='site',
        ),
        migrations.AlterField(
            model_name='education',
            name='org',
            field=models.ForeignKey(max_length=80, on_delete=django.db.models.deletion.CASCADE, to='MainApp.StudyPlace', verbose_name='Place of study'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Employer', verbose_name='Employer'),
        ),
    ]
