# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20160707_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.StudyPlace', verbose_name='Place of study'),
        ),
    ]
