# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_auto_20160707_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='classname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Class name'),
        ),
    ]
