# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_education_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 13, 13, 47, 24, 927057, tzinfo=utc), verbose_name='Date of start'),
            preserve_default=False,
        ),
    ]
