# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_experience_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employer_location',
            field=models.URLField(max_length=300, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='studyplace',
            name='stp_location',
            field=models.URLField(max_length=300, verbose_name='Location'),
        ),
    ]
