# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='img',
            field=models.URLField(blank=True, null=True, verbose_name='Image'),
        ),
    ]
