# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_projects_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 14, 18, 40, 12, 204358, tzinfo=utc), verbose_name='Date of start'),
            preserve_default=False,
        ),
    ]
