# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_education_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=100, verbose_name='Degree'),
        ),
    ]
