# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_auto_20160822_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employer_location',
            field=models.URLField(max_length=500, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='studyplace',
            name='stp_location',
            field=models.URLField(max_length=500, verbose_name='Location'),
        ),
    ]
