# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employer_place',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
    ]
